- name: Setup ec2 or vm for full devops application 
  hosts: servers
  become: true
  gather_facts: true

  tasks:
    # - name: debug 
    #   debug:
    #     msg: "{{ ansible_facts.env.PWD }}"

      
    # - name: Install common pkgs 
    #   import_role:
    #     name: common
    
    # - name: Install Docker
    #   import_role: 
    #     name: docker

    # - name: Install Kind 
    #   import_role:
    #     name: kind 

    # - name: Install Kubectl  
    #   import_role:
    #     name: kubectl

    # - name: Install helm  
    #   import_role:
    #     name: helm

    # - name: Create kind cluster 
    #   import_role:
    #     name: kindCluster 
    #   become: false
      # explicitly added because i want kind to be present in normal user not root
      #  because kind writes kubeconfig to user's home directory
      # with become:true it gets created under /root/.kube/config and is inaccessible to normal user.


    # - name: Install Gateway CRD and envoy 
    #   import_role: 
    #     name: gateway
    #   become: false

    - name: Install Argocd and initiate app deployment
      import_role:
        name: argocd
      become: false

