
services:
  frontend:
    image: hackerspider09/ecom-frontend:latest
    # latest tag: uses dev dockerfile
    # prod tag: uses prod dockerfile
    
    ports:
      - "80:80"
      - "5173:5173"

    environment:
      VITE_USER_SERVICE_URL: http://user-service:8000
      VITE_PRODUCT_SERVICE_URL: http://product-service:3001
      VITE_ORDER_SERVICE_URL: http://order-service:8082

    depends_on:
      - user-service
      - product-service
      - order-service

  # Databases
  user-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "userdb"
    expose:
      - 5432
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  
  product-db:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_DATABASE: productdb

    expose:
      - 27017

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  order-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orderdb
    expose:
      - 5432
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d orderdb"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  redis:
    image: redis:alpine
    expose:
      - 6379

  # Services 
  user-service:
    image: hackerspider09/ecom-userservice:latest
    environment:
      DATABASE_URL: "postgresql://admin:admin@user-db:5432/userdb"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    expose:
      - 8000
    depends_on:
      user-db:
        condition: service_healthy
  product-service:
    image: hackerspider09/ecom-productservice:latest
    environment:
      MONGODB_URI: "mongodb://admin:admin@product-db:27017/productdb?authSource=admin"
    expose:
      - 3001
    depends_on:
      product-db: 
        condition: service_healthy
    
  seed-service:
    image: hackerspider09/ecom-productservice:latest
    environment:
      MONGODB_URI: "mongodb://admin:admin@product-db:27017/productdb?authSource=admin"

    depends_on:
      product-db: 
        condition: service_healthy
    command: ["npm", "run", "seed"]

  order-service:
    image: hackerspider09/ecom-orderservice:latest
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://order-db:5432/orderdb" 
      SPRING_DATASOURCE_USERNAME: admin 
      SPRING_DATASOURCE_PASSWORD: admin
      PRODUCT_SERVICE_URL: "http://product-service:3001"
    expose:
      - 8082

    depends_on:
      order-db: 
        condition: service_healthy

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    # expose:
    # - 8080
    ports:
    - "8080:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # these are arguments passed
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
