- name: Get latest kubectl version
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_version


- name: Download kubectl
  get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/{{system_arch}}/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'


  #  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
