kind: Deployment
apiVersion: apps/v1

# Note: if react application is already build and usedby nginx it will not accept env as it resolve env at building time not runtime
# so i am using dev dockerfile

# service name resolve inside k8s cluster and frontend makes request from browser so that service is not accesible 
# to make it accessible use loadbalancer, ingress, nodeport
metadata:
  name: frontendservice-deployment
  namespace: ms-ecom-application
  labels:
    app: frontend
    tier: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend
      tier: frontend

  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
        - name: frontend-app
          image: hackerspider09/ecom-frontend:latest
          ports:
            - containerPort: 80
            - containerPort: 5173
          env:
            - name: VITE_USER_SERVICE_URL
              value: "http://userservice-service:8000"

          # for debug only 
          imagePullPolicy: Never
