spring.application.name=order-service
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://order-db:5432/orderdb}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orderdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${SERVER_PORT:8082}

# Service URLs
# user.service.url=${USER_SERVICE_URL:http://user-service:8000}
# product.service.url=${PRODUCT_SERVICE_URL:http://product-service:3001}
# changed to identify which url its taking fro here or env
user.service.url=${USER_SERVICE_URL:http://user-service:8000}
product.service.url=${PRODUCT_SERVICE_URL:http://product-service:3001}
