

# kubernetes ansible modules need python kubernetes libs
# those libs are installed inside our virtualenv
# so for below tasks we override ansible's python interpreter
# otherwise ansible uses system python (/usr/bin/python3)
# and kubernetes module import fails

- name: Install gateway resources
  block:

    # kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
    - name: Install gateway CRD
      kubernetes.core.k8s:
        src: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.0/standard-install.yaml
        state: present

    # helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.0.0-latest -n envoy-gateway-system --create-namespace
    - name: Install envoy gateway
      kubernetes.core.helm:
        name: eg
        chart_version: v0.0.0-latest
        chart_ref: oci://docker.io/envoyproxy/gateway-helm
        release_namespace: envoy-gateway-system
        create_namespace: true
        wait: true

  vars:
    # force ansible to use python from our virtual env
    # this python already has kubernetes/openshift/pyyaml installed
    ansible_python_interpreter: "{{ k8s_venv_path }}/bin/python"