name: 01 Frontend workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - cicd
    paths:
      - 'frontend/**'
          

env:
  dir_name: "frontend"
  branch_name: "main"
  language: "javascript"
  image_name: "ecom-frontend"
  dockerfile_name: "Dockerfile.prod"

permissions:
  # permission added for codeql security scan
  contents: read
  security-events: write

jobs:
  setup:
    # This is used to set env variable to access in reusable jobs
    # as env context is not inside with
    runs-on: ubuntu-latest
    outputs:
      dir_name: ${{env.dir_name}}
      branch_name: ${{env.branch_name}}
      language: ${{env.language}}
      image_name: ${{env.image_name}}
      dockerfile_name: ${{env.dockerfile_name}}
    steps:
      - run: echo "Setup completed..."


  secret-scan:
    needs: setup
    uses: ./.github/workflows/secrets-scan.yaml
    with:
      branch_name: ${{ needs.setup.outputs.branch_name }}

  # code-quality:
  #   needs: setup
  #   uses: ./.github/workflows/code-scan.yaml
  #   with:
  #     branch_name: ${{ needs.setup.outputs.branch_name }}
  #     service_lang: ${{ needs.setup.outputs.language }}
  #     dir_name: ${{ needs.setup.outputs.dir_name }}

  build-scan:
    # needs: code-quality
    uses: ./.github/workflows/build-scan-push.yaml
    with:
      branch_name: ${{ needs.setup.outputs.branch_name }}
      service_lang: ${{ needs.setup.outputs.language }}
      dir_name: ${{ needs.setup.outputs.dir_name }}
      image_name: ${{ needs.setup.outputs.image_name }}
      dockerfile_name: ${{ needs.setup.outputs.dockerfile_name }}

    secrets: inherit

