name: Code quality check

on:
  workflow_call:
    inputs:
      branch_name:
        description: Use to checkout to specific branch
        type: string
        default: main
      service_lang:
        description: Language of application/service to setup for scans
        type: string
        required: true
      dir_name:
        description: Dir of code
        type: string
        required: true
        
    
jobs:
    
  code-scan:
    # perform sast
    runs-on: ubuntu-latest

    defaults:
      run:
        # this will work only in run, doesnt work in uses:
        working-directory: ${{ inputs.dir_name }}

        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch_name }}
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ inputs.service_lang }}
          config: |
            paths: 
              - ${{ inputs.dir_name }}

      # - name: Autobuild
      #   uses: github/codeql-action/autobuild@v4

      #  for java debug
      - name: Build with Maven (debug mode)
        run: |
          mvn clean package -DskipTests

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4


  dependency-scan:
    # Perform cve scan for lib/pkgs by trivy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.dir_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch_name }}

      - name: Dependency scan 
        uses: aquasecurity/trivy-action@0.35.0
        with:
          exit-code: '1'
          severity: 'CRITICAL'  # can add multiple by comma seperated in same string ' x,y,z'
          scan-type: 'fs'  # dcan the filesystem
          scan-ref: ${{ inputs.dir_name }} # scan in specified dir

