name: Secrets scan

on:
  workflow_call:
    inputs:
      branch_name:
        description: Use to checkout to specific branch
        type: string
        default: main
jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{inputs.branch_name}}

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

